### ISSUE TITLE
Find educational literature

### ISSUE THREAD

**Issue by NervzZ** [NervzZ/Designing-learning-tools-project#10]

**Comment by lipefree** [comment]
[Designing and Using Games to
Teach Ethics and Ethical Thinking, 2014](https://arcabc.ca/islandora/object/mru%3A151/datastream/PDF/view#page=148)

This is a chapter from the book *Learning, Education and Games* by **Karen Schrier**. It contains several examples of implemented games teaching ethics and detailing key features that has to be added to enhance the experience and learning. We can use this book to choose what feature is the most relevant to implement.

[Serious Games to Teach Ethics, 2009](https://csuepress.columbusstate.edu/cgi/viewcontent.cgi?article=2055&context=bibliography_faculty)

This paper is more focused on the overall architecture of the game. It proposes an architecture that contains 2 level : Tutoring level and the Narrative level. This paper can help us designing the story and stay consistent with the educational aspects. 

[Designing Serious Games to Teach Ethics to Young Children](https://www.sciencedirect.com/science/article/pii/S1877050921000892)

This is an implementations of a game to teach ethics while using concepts from game design for education. We can use it as a real example of a final game. 

[The Six Facets of Serious Game Design](https://link.springer.com/chapter/10.1007/978-3-642-33263-0_17) 

The last paper was using this book as a reference. Since our game will be different from the previous one, when we are hesitant on whether we should implement a feature and how, we can fall back to this book as a guide.

**Comment by lipefree** [comment]
I think these 4 resources are complete enough for us. For example, when someone is designing to story, he should take a look at *Serious GAmes to Teach ethics* to adapt the story so that it can be more effective to teach ethics.
