### ISSUE TITLE
Meeting discussions 17:00

### ISSUE THREAD

**Issue by NervzZ** [NervzZ/Designing-learning-tools-project#12]

**Comment by simi48** [comment]
Hey yall,
I would love to quickly discuss #5, and see if we can fix a general topic/theme so that we can then work more specifically on the story




Also, we should probably quickly address the points they mentioned in the mail:

1. everyone has completed the Interdisciplinary project management questionnaire and used this to set learning targets for yourself around team and project management. 
2. Each team would normally be completing (or have completed) one of the process analysis tasks for the portfolio
3. Your scoping of the potential solutions has well progressed and you are soon turning your attention towards planning and report writing
