### ISSUE TITLE
Brainstorm key ideas for game storyline / content

### ISSUE THREAD

**Issue by NervzZ** [NervzZ/Designing-learning-tools-project#5]

**Comment by simi48** [comment]
Ideas:
1. city-builder kind game, with questionable energy source, waste disposal or sth, kills all bees or whatever
2. Cure for cancer, but you realize it kills Asians (ignites racism, classism etc if you go public, but otherwise they die)
3. "Tangible" issues from civil engineering, like building a bridge goes wrong but you can't afford to fix it, a dam killing fish after you spent years to make it Eco-friendly and everyone thinks its genius.
4. "Futuristic" stuff like invent teleportation device, but then it gets used for surveillance and data collection which is then misused by corporations and government (could be extended to include some extortion if you try to backtrack) (also kinda works for digital SBB tickets)
5. AI/Quantum Computers/some technology breaks RSA(or some other important thing everyone relies on)
6. "Invent a money printing press" like turn dirt to gold, extract oil from water kinda things, global economy collapses or climatechange creates issues or sth.
7. Something a bit simpler where invention is good, but you get greedy and things go bad.


story branches:
1. make patent or opensource (you run out of money to research, and a patent could give you funds)
2. Research more or release ASAP (maybe u have competitor?)
3. Tell the public you fucked up or try to fix it quietly
4.

Just some other story ideas
1. someone steals your idea and profits from your work
2. 2 similar systems, yours is super safe and the other is not, but the public thinks yours is dangerous.

Do we even want branches ? i.e. the teleportation could be a non-branching well thought out story (perhaps illusion of choice)

**Comment by lipefree** [comment]
I like your ideas but why the second one has to target asians :skull:. For your question about branching, a lot of games that teaches ethics do it and it has some benefits for the student (i.e. improve immersion, etc.), if you are lacking ideas about how the story line should look like in more details you can refer to #10 !

**Comment by simi48** [comment]
Ok, after looking at #10, I feel like for the story it might be beneficial to have like 2 coworkers, one of them pushing you to do good, and one pushing you to make the bad choices, and like 90% of the interaction/discussion is with them, and only 10% actually affect the environment.

I feel like this would be beneficial for 2 reasons:
1. It would make our lives easier
2. Human interaction is a lot more tangible and relatable than some abstract consequences to some fantasy world in a short game

Also splitting the architecture into tutoring and narrative (as proposed in  [Serious Games to Teach Ethics, 2009](https://csuepress.columbusstate.edu/cgi/viewcontent.cgi?article=2055&context=bibliography_faculty)) seems like too much overhead to be feasible.
