### ISSUE TITLE
Add Assets to Godot

### ISSUE THREAD

**Issue by Neroxsis** [NervzZ/Designing-learning-tools-project#91]
Add couple of the assets of #59 and create scenes from it.

**Comment by Neroxsis** [comment]
Created two levels, one for lab and the other for a house.
Colliders are already in place due to the tilemap. Still need to check how to set the colliders such that they interact with the player.

**Comment by Neroxsis** [comment]
Please check out branch and give feedback

**Comment by simi48** [comment]
Looks really cool!

Also just reminded me, since it looks like we can walk out of the scene, are we planning to load in a new a new scene, or do we want like big maps with the camera following the player?


I think our (square) player is too big for the maps (or at least the hitbox is too big), like I get stuck between 2 parts of the same level, but I guess this'll get fixed for free when we change the player character

**Comment by Neroxsis** [comment]
Iirc, we wanted to have some exploration in one dimension. That is why I build the level a bit larger on the sides. I'd say the camera only follows the player if he moves from left to right, while there is more of the level to show in that direction, not when he is moving up and down.

So no big maps, just some movement from left to right for optional exploration.

The house and the lab are meant to be two different levels / scenes, so they will be loaded. I didn't mean for the player to walk from the lab to the house and vice versa. 

I agree that the player is a bit big atm.
